chore: fix number and bigint coercion
edmundhung/conform pull request #726
Opened 2024-08-02 03:11 UTC by lifeiscontent

2024-08-08 20:10 UTC, edmundhung requested changes
Thanks for the PR! The changes for BigInt makes sense to me but maybe we should keep the number coercion untouched.

2024-08-08 20:10 UTC, edmundhung commented on tests/conform-zod.spec.ts
> -				error: { test: ['invalid'] },
This is exactly what we are trying to avoid with `.trim()`

2024-08-09 19:59 UTC, lifeiscontent commented
@edmundhung fixed

2024-08-10 11:58 UTC, edmundhung submitted a review, later dismissed
Looks good to me. Thank you!

2024-09-10 22:05 UTC, edmundhung approved these changes

2024-09-10 22:24 UTC, merged